inherit_gem:
  rubocop-shopify: rubocop.yml
  shopify-types: rubocop.yml

AllCops:
  Exclude:
    - bin/*
    - node_modules/**/*
    - db/schema.rb
  NewCops: disable
  SuggestExtensions: false

Sorbet/ForbidSuperclassConstLiteral:
  Exclude:
    - db/migrate/*.rb
    - db/lhm/*.rb
